### ISSUE TITLE
Could not read in entire checksum file - Port test helper to Rust (or debug this)

### ISSUE THREAD

**Issue by nathanaeljones** [imazen/imageflow#107]
```
failures:
---- test_expand_rect stdout ----
	Error 20 I/O Error : Could not read in entire checksum file. Please increase list_size above 26l.
helpers_visual.c:132: in function load_checksums
helpers_visual.c:182: in function get_checksum_for
thread 'test_expand_rect' panicked at 'explicit panic', src\context.rs:753
stack backtrace:
   0:   0x63dcfb - std::panicking::default_hook
                at C:\bot\slave\nightly-dist-rustc-win-msvc-32\build\src\libstd\panicking.rs:257
   1:   0x63e60a - std::panicking::rust_panic_with_hook
                at C:\bot\slave\nightly-dist-rustc-win-msvc-32\build\src\libstd\panicking.rs:451
   2:   0x4818ac - std::panicking::begin_panic<&str>
                at C:\bot\slave\nightly-dist-rustc-win-msvc-32\build\src\libstd\panicking.rs:413
   3:   0x5b9b5c - imageflow_core::context::ContextPtr::assert_ok
                at C:\projects\imageflow\imageflow_core\src\context.rs:753
   4:   0x3f5e39 - visuals::compare
                at C:\projects\imageflow\imageflow_core\tests\visuals.rs:116
   5:   0x3f6a02 - visuals::test_expand_rect
                at C:\projects\imageflow\imageflow_core\tests\visuals.rs:136
   6:   0x5febca - test::{{impl}}::call_box<(),closure>
                at C:\bot\slave\nightly-dist-rustc-win-msvc-32\build\src\libtest\lib.rs:141
   7:   0x5f2cad - std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure>,()>
                at C:\bot\slave\nightly-dist-rustc-win-msvc-32\build\src\libstd\panicking.rs:352
   8:   0x64242b - panic_unwind::__rust_maybe_catch_panic
                at C:\bot\slave\nightly-dist-rustc-win-msvc-32\build\src\libpanic_unwind\lib.rs:97
   9:   0x5f2ea5 - std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure>,()>
                at C:\bot\slave\nightly-dist-rustc-win-msvc-32\build\src\libstd\panicking.rs:352
  10:   0x64242b - panic_unwind::__rust_maybe_catch_panic
                at C:\bot\slave\nightly-dist-rustc-win-msvc-32\build\src\libpanic_unwind\lib.rs:97
  11:   0x5f9c5b - alloc::boxed::{{impl}}::call_box<(),closure>
                at C:\bot\slave\nightly-dist-rustc-win-msvc-32\build\src\liballoc\boxed.rs:595
  12:   0x63cb7c - std::sys::imp::thread::{{impl}}::new::thread_start
                at C:\bot\slave\nightly-dist-rustc-win-msvc-32\build\src\libstd\sys\windows\thread.rs:50
  13: 0x76607c03 - BaseThreadInitThunk
  14: 0x77bcab8e - RtlInitializeExceptionChain
```

**Comment by nathanaeljones** [comment]
Ported the entire framework to Rust. Same error. Turns out, rust runs all tests in parallel, and the OS wasn't syncing access to the file very well.
