### ISSUE TITLE
Problem serving files, using Docker imazen/imageflow_server_unsecured/

### ISSUE THREAD

**Issue by yohanyflores** [imazen/imageflow#153]
I'm testing from imazen/imageflow_server_unsecured /, and it works fine for some images, but for others not.

```
 start    --bind-address 0.0.0.0 \
            --port 39876 \
            --data-dir /tuvoti/data-dir \
            --mount "/tuvoti/:ir4_local:/tuvoti/public-medias"
```

The next image fails to request it without any transformation.

![imo-3](https://user-images.githubusercontent.com/2650124/31182064-e1c54784-a8f0-11e7-8bb3-833bba872975.png)

imageflow_server responds with:

GET https:/localhost:39876/img/slider/imo-3.png

```
Internal Server ErrorInfo:"/public-medias/img/slider/imo-3.png"Error:BuildFailure(Error { httpish_code: 500, message: "" })
```
 into log:

```
 libpng warning: iCCP: known incorrect sRGB profile
 libpng warning: iCCP: known incorrect sRGB profile
 thread '<unnamed>' panicked at 'internal error: entered unreachable code: Profile source should never be set to ICCP without a profile buffer', imageflow_core/src/codecs/mod.rs:469:20
 note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
 stack backtrace:
    0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
              at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
    1: std::sys_common::backtrace::_print
              at /checkout/src/libstd/sys_common/backtrace.rs:71
    2: std::panicking::default_hook::{{closure}}
              at /checkout/src/libstd/sys_common/backtrace.rs:60
              at /checkout/src/libstd/panicking.rs:380
    3: std::panicking::default_hook
              at /checkout/src/libstd/panicking.rs:396
    4: std::panicking::rust_panic_with_hook
              at /checkout/src/libstd/panicking.rs:610
    5: std::panicking::begin_panic
              at /checkout/src/libstd/panicking.rs:571
    6: std::panicking::begin_panic_fmt
              at /checkout/src/libstd/panicking.rs:521
    7: imageflow_core::codecs::ColorTransformCache::hash
              at imageflow_core/src/codecs/mod.rs:469
    8: <imageflow_core::codecs::ClassicDecoder as imageflow_core::codecs::Decoder>::read_frame
              at imageflow_core/src/codecs/mod.rs:515
              at imageflow_core/src/codecs/mod.rs:207
    9: <imageflow_core::flow::nodes::codecs_and_pointer::DecoderPrimitiveDef as imageflow_core::flow::definitions::NodeDef>::execute
              at imageflow_core/src/flow/nodes/codecs_and_pointer.rs:204
   10: imageflow_core::flow::execution_engine::Engine::execute_many
              at imageflow_core/src/flow/execution_engine.rs:457
              at imageflow_core/src/flow/execution_engine.rs:157
              at imageflow_core/src/flow/execution_engine.rs:92
   11: imageflow_core::context::Context::execute_1
              at imageflow_core/src/context.rs:234
   12: imageflow_core::clients::stateless::LibClient::build_inner
              at imageflow_core/src/clients/stateless.rs:127
   13: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
              at imageflow_core/src/clients/stateless.rs:155
              at /checkout/src/libstd/panic.rs:296
   14: std::panicking::try::do_call
              at /checkout/src/libstd/panicking.rs:479
   15: __rust_maybe_catch_panic
              at /checkout/src/libpanic_unwind/lib.rs:98
   16: std::panicking::try
              at /checkout/src/libstd/panicking.rs:458
   17: std::panic::catch_unwind
              at /checkout/src/libstd/panic.rs:361
   18: imageflow_core::clients::stateless::LibClient::build
              at imageflow_core/src/clients/stateless.rs:154
   19: imageflow_server::ir4_local_respond
              at imageflow_server/src/lib.rs:297
              at imageflow_server/src/lib.rs:322
              at imageflow_server/src/lib.rs:386
   20: imageflow_server::ir4_local_handler
              at imageflow_server/src/lib.rs:396
   21: <F as iron::middleware::Handler>::handle
              at imageflow_server/src/lib.rs:532
              at /home/conan/.cargo/registry/src/github.com-1ecc6299db9ec823/iron-0.5.1/src/middleware/mod.rs:312
   22: <alloc::boxed::Box<iron::middleware::Handler + 'static> as iron::middleware::Handler>::handle
              at /home/conan/.cargo/registry/src/github.com-1ecc6299db9ec823/iron-0.5.1/src/middleware/mod.rs:318
   23: <mount::mount::Mount as iron::middleware::Handler>::handle
              at /home/conan/.cargo/git/checkouts/mount-e3fe55b55b7ad7b2/2c3d719/src/mount.rs:122
   24: iron::middleware::Chain::continue_from_handler
              at /home/conan/.cargo/registry/src/github.com-1ecc6299db9ec823/iron-0.5.1/src/middleware/mod.rs:318
              at /home/conan/.cargo/registry/src/github.com-1ecc6299db9ec823/iron-0.5.1/src/middleware/mod.rs:282
   25: iron::middleware::Chain::continue_from_before
              at /home/conan/.cargo/registry/src/github.com-1ecc6299db9ec823/iron-0.5.1/src/middleware/mod.rs:276
   26: <iron::middleware::Chain as iron::middleware::Handler>::handle
              at /home/conan/.cargo/registry/src/github.com-1ecc6299db9ec823/iron-0.5.1/src/middleware/mod.rs:200
   27: <iron::iron::RawHandler<H> as hyper::server::Handler>::handle
              at /home/conan/.cargo/registry/src/github.com-1ecc6299db9ec823/iron-0.5.1/src/iron.rs:176
   28: <hyper::server::Worker<H>>::handle_connection
              at /home/conan/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.10.12/src/server/mod.rs:337
              at /home/conan/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.10.12/src/server/mod.rs:283
```

What am I doing wrong? I'm missing some configuration?

**Comment by yohanyflores** [comment]
Full stack trace

```
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    | libpng warning: iCCP: known incorrect sRGB profile
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    | libpng warning: iCCP: known incorrect sRGB profile
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    | thread '<unnamed>' panicked at 'internal error: entered unreachable code: Profile source should never be set to ICCP without a profile buffer', imageflow_core/src/codecs/mod.rs:469:20
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    | stack backtrace:
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |    0:       0x735a09eb73 - std::sys::imp::backtrace::tracing::imp::unwind_backtrace::h7a155cd9ef8da4bd
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |                                at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |    1:       0x735a09abf4 - std::sys_common::backtrace::_print::h06c4e4bd0de4ff1f
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |                                at /checkout/src/libstd/sys_common/backtrace.rs:71
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |    2:       0x735a0a3343 - std::panicking::default_hook::{{closure}}::hc19d0dda484e6ea4
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |                                at /checkout/src/libstd/sys_common/backtrace.rs:60
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |                                at /checkout/src/libstd/panicking.rs:380
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |    3:       0x735a0a30a2 - std::panicking::default_hook::h7901edc1e19001df
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |                                at /checkout/src/libstd/panicking.rs:396
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |    4:       0x735a0a3847 - std::panicking::rust_panic_with_hook::h19e0f627719dfef6
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |                                at /checkout/src/libstd/panicking.rs:610
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |    5:       0x735a0a3714 - std::panicking::begin_panic::h8ecefb239c9021ed
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |                                at /checkout/src/libstd/panicking.rs:571
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |    6:       0x735a0a3619 - std::panicking::begin_panic_fmt::h152aa7f1779e3735
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |                                at /checkout/src/libstd/panicking.rs:521
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |    7:       0x7359f060e3 - imageflow_core::codecs::ColorTransformCache::hash::hfff3bf11f8cd9ee7
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |                                at imageflow_core/src/codecs/mod.rs:469
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |    8:       0x7359f02df9 - <imageflow_core::codecs::ClassicDecoder as imageflow_core::codecs::Decoder>::read_frame::hcc80df87ec055b71
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |                                at imageflow_core/src/codecs/mod.rs:515
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |                                at imageflow_core/src/codecs/mod.rs:207
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |    9:       0x7359eb670e - <imageflow_core::flow::nodes::codecs_and_pointer::DecoderPrimitiveDef as imageflow_core::flow::definitions::NodeDef>::execute::hf449f22a3dd543a4
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |                                at imageflow_core/src/flow/nodes/codecs_and_pointer.rs:204
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |   10:       0x7359ea8808 - imageflow_core::flow::execution_engine::Engine::execute_many::h16b15e18f82e334b
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |                                at imageflow_core/src/flow/execution_engine.rs:457
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |                                at imageflow_core/src/flow/execution_engine.rs:157
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |                                at imageflow_core/src/flow/execution_engine.rs:92
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |   11:       0x7359e99990 - imageflow_core::context::Context::execute_1::h0e868cb30bcde14a
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |                                at imageflow_core/src/context.rs:234
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |   12:       0x7359e93236 - imageflow_core::clients::stateless::LibClient::build_inner::h6550b3552ae66c67
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |                                at imageflow_core/src/clients/stateless.rs:127
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |   13:       0x7359ee997f - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h45705e1f9611c183
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |                                at imageflow_core/src/clients/stateless.rs:155
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |                                at /checkout/src/libstd/panic.rs:296
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |   14:       0x7359eea3e9 - std::panicking::try::do_call::h2b42ab321cccdf22
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |                                at /checkout/src/libstd/panicking.rs:479
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |   15:       0x735a0aa94c - __rust_maybe_catch_panic
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |                                at /checkout/src/libpanic_unwind/lib.rs:98
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |   16:       0x7359eea1de - std::panicking::try::h13b001e6c3248b53
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |                                at /checkout/src/libstd/panicking.rs:458
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |   17:       0x7359ee9c0c - std::panic::catch_unwind::hcd37b6c2d4737d17
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |                                at /checkout/src/libstd/panic.rs:361
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |   18:       0x7359e94597 - imageflow_core::clients::stateless::LibClient::build::h7689a736c7e42cdc
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |                                at imageflow_core/src/clients/stateless.rs:154
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |   19:       0x7359e4bb00 - imageflow_server::ir4_local_respond::h23d552200179b416
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |                                at imageflow_server/src/lib.rs:297
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |                                at imageflow_server/src/lib.rs:322
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |                                at imageflow_server/src/lib.rs:386
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |   20:       0x7359e420e7 - imageflow_server::ir4_local_handler::he9ec088ee1502d12
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |                                at imageflow_server/src/lib.rs:396
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |   21:       0x7359e48cab - <F as iron::middleware::Handler>::handle::ha21ba595cb840fd7
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |                                at imageflow_server/src/lib.rs:532
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |                                at /home/conan/.cargo/registry/src/github.com-1ecc6299db9ec823/iron-0.5.1/src/middleware/mod.rs:312
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |   22:       0x735a032535 - <alloc::boxed::Box<iron::middleware::Handler + 'static> as iron::middleware::Handler>::handle::h8f0501df9ddd0448
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |                                at /home/conan/.cargo/registry/src/github.com-1ecc6299db9ec823/iron-0.5.1/src/middleware/mod.rs:318
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |   23:       0x7359f20dca - <mount::mount::Mount as iron::middleware::Handler>::handle::h25d7087c324a39bf
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |                                at /home/conan/.cargo/git/checkouts/mount-e3fe55b55b7ad7b2/2c3d719/src/mount.rs:122
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |   24:       0x735a031f86 - iron::middleware::Chain::continue_from_handler::heefba535481d10f6
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |                                at /home/conan/.cargo/registry/src/github.com-1ecc6299db9ec823/iron-0.5.1/src/middleware/mod.rs:318
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |                                at /home/conan/.cargo/registry/src/github.com-1ecc6299db9ec823/iron-0.5.1/src/middleware/mod.rs:282
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |   25:       0x735a031b4a - iron::middleware::Chain::continue_from_before::h5aa74625105c4db4
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |                                at /home/conan/.cargo/registry/src/github.com-1ecc6299db9ec823/iron-0.5.1/src/middleware/mod.rs:276
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |   26:       0x735a03169f - <iron::middleware::Chain as iron::middleware::Handler>::handle::hef4d8611de4fd2ec
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |                                at /home/conan/.cargo/registry/src/github.com-1ecc6299db9ec823/iron-0.5.1/src/middleware/mod.rs:200
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |   27:       0x7359e4e810 - <iron::iron::RawHandler<H> as hyper::server::Handler>::handle::h0154f43254c61378
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |                                at /home/conan/.cargo/registry/src/github.com-1ecc6299db9ec823/iron-0.5.1/src/iron.rs:176
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |   28:       0x7359e7646b - <hyper::server::Worker<H>>::handle_connection::h54f225ca5a7f6269
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |                                at /home/conan/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.10.12/src/server/mod.rs:337
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |                                at /home/conan/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.10.12/src/server/mod.rs:283
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |   29:       0x7359e833b9 - std::sys_common::backtrace::__rust_begin_short_backtrace::h1e063199bb673fba
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |                                at /home/conan/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.10.12/src/server/mod.rs:242
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |                                at /home/conan/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.10.12/src/server/listener.rs:50
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |                                at /checkout/src/libstd/sys_common/backtrace.rs:136
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |   30:       0x7359e7d7b7 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h14145b07880d34d4
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |                                at /checkout/src/libstd/thread/mod.rs:364
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |                                at /checkout/src/libstd/panic.rs:296
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |   31:       0x7359e5c9d7 - std::panicking::try::do_call::h7b87d263f896884e
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |                                at /checkout/src/libstd/panicking.rs:479
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |   32:       0x735a0aa94c - __rust_maybe_catch_panic
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |                                at /checkout/src/libpanic_unwind/lib.rs:98
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |   33:       0x7359e5c80a - std::panicking::try::hedf23d5db27c14d9
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |                                at /checkout/src/libstd/panicking.rs:458
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |   34:       0x7359e7d94b - std::panic::catch_unwind::h1846a087c0c9f62f
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |                                at /checkout/src/libstd/panic.rs:361
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |   35:       0x7359e8604a - <F as alloc::boxed::FnBox<A>>::call_box::h2e84ad8ca5191835
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |                                at /checkout/src/libstd/thread/mod.rs:363
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |                                at /checkout/src/liballoc/boxed.rs:682
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |   36:       0x735a0a273b - std::sys::imp::thread::Thread::new::thread_start::h31297917bc604686
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |                                at /checkout/src/liballoc/boxed.rs:692
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |                                at /checkout/src/libstd/sys_common/thread.rs:21
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |                                at /checkout/src/libstd/sys/unix/thread.rs:84
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |   37:     0x7f1013eee6b9 - start_thread
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |   38:     0x7f1013a0e3dc - clone
imk-tuvoti-media.1.fchl2fi7ikx4@leon-rojo    |   39:                0x0 - <unknown>
```

**Comment by nathanaeljones** [comment]
Thank you for sharing this image! Is it OK if I add this to a regression test suite?

**Comment by yohanyflores** [comment]
Thanks for resolve the problem!

Feel free to include the image in the test suite.  Glad to collaborate!
