### ISSUE TITLE
Test bitmaps > 2GB

### ISSUE THREAD

**Issue by lilith** [imazen/imageflow#192]
Test bitmaps whose floating-point representations exceed 2GB/4GB in size.

**Comment by lilith** [comment]
Pretty much guaranteed not to work on 32-bit due to usize. 

https://www.bamsoftware.com/hacks/deflate.html

**Comment by zlepper** [comment]
I'm investigating Imageflow as an alternative to our current imagemagick implementation. So a "quick" test a threw a 500 MB jpg I have at Imageflow. After tweaking the security option i encountered this exact issue. Strange thing however is that i'm using a 64-bit build of Imageflow (At least according to the nuget package name: `<PackageReference Include="Imageflow.NativeRuntime.win-x86_64" Version="1.5.5-rc59"/>`
Our clients still aren't at that image size yet, but we are starting to regularly encounter images of rather large sizes. 

Image can be found here: https://digieyez-my.sharepoint.com/:i:/g/personal/rhdh_digidom_dk/EeORvEE5bIpJijEDfkWkEXkBXl22X-Jd77CSlSojzRTUOA?e=Jrfhx7

Imagemagick handles this image just fine, even if it uses a bit more RAM than we would like.

**Comment by lilith** [comment]
What error message do you get?

**Comment by zlepper** [comment]
Output from running a small C# app trying to resize the above image. 
```
C:\Users\Rasmus\AppData\Local\JetBrains\Toolbox\apps\Rider\ch-0\203.6682.13\plugins\dpa\DotFiles\JetBrains.DPA.Runner.exe --handle=4392 --backend-pid=15648 --detach-event-name=dpa.detach.4392 "C:\Program Files\dotnet\dotnet.exe" C:/dev/fun/ConsoleApp2/ConsoleApp2/bin/Release/net5.0/ConsoleApp2.dll
Unhandled exception. Imageflow.Bindings.ImageflowException: ArgumentInvalid: InvalidArgument: Bitmap dimensions cannot be so large they would cause i32 overflow at
imageflow_core\src\graphics\bitmaps.rs:416:24
https://github.com/imazen/imageflow/blob/d384d92d9ccfa02c44a32c25c4eea512f3ff1216/imageflow_core\src\graphics\bitmaps.rs#L416
imageflow_core\src\graphics\bitmaps.rs:436:67
https://github.com/imazen/imageflow/blob/d384d92d9ccfa02c44a32c25c4eea512f3ff1216/imageflow_core\src\graphics\bitmaps.rs#L436
imageflow_core\src\codecs\mozjpeg_decoder.rs:116:31
https://github.com/imazen/imageflow/blob/d384d92d9ccfa02c44a32c25c4eea512f3ff1216/imageflow_core\src\codecs\mozjpeg_decoder.rs#L116
imageflow_core\src\flow\nodes\codecs_and_pointer.rs:222:65
https://github.com/imazen/imageflow/blob/d384d92d9ccfa02c44a32c25c4eea512f3ff1216/imageflow_core\src\flow\nodes\codecs_and_pointer.rs#L222
imageflow_core\src\flow\execution_engine.rs:477:114
https://github.com/imazen/imageflow/blob/d384d92d9ccfa02c44a32c25c4eea512f3ff1216/imageflow_core\src\flow\execution_engine.rs#L477
imageflow_core\src\context.rs:419:59
https://github.com/imazen/imageflow/blob/d384d92d9ccfa02c44a32c25c4eea512f3ff1216/imageflow_core\src\context.rs#L419
imageflow_core\src\context_methods.rs:50:68
https://github.com/imazen/imageflow/blob/d384d92d9ccfa02c44a32c25c4eea512f3ff1216/imageflow_core\src\context_methods.rs#L50
Active node:
NodeDebugInfo {
    stable_id: 0,
    params: Json(
        Decode {
            io_id: 0,
            commands: None,
        },
    ),
    index: NodeIndex(0),
}


   at Imageflow.Bindings.JobContext.AssertReady()
   at Imageflow.Bindings.JobContext.SendJsonBytes(String method, Byte[] utf8Json)
   at Imageflow.Bindings.JobContext.Execute[T](T message)
   at Imageflow.Fluent.ImageJob.FinishAsync(JobExecutionOptions executionOptions, SecurityOptions securityOptions, CancellationToken cancellationToken)
   at ConsoleApp2.Program.Manipulate() in C:\dev\fun\ConsoleApp2\ConsoleApp2\Program.cs:line 35
   at ConsoleApp2.Program.Manipulate() in C:\dev\fun\ConsoleApp2\ConsoleApp2\Program.cs:line 42
   at ConsoleApp2.Program.Manipulate() in C:\dev\fun\ConsoleApp2\ConsoleApp2\Program.cs:line 42
   at ConsoleApp2.Program.Main(String[] args) in C:\dev\fun\ConsoleApp2\ConsoleApp2\Program.cs:line 19
   at ConsoleApp2.Program.<Main>(String[] args)

```


Code:

```c#
using var job = new ImageJob();
await using var input = File.OpenRead("C:/stuffs/large.jpg");
await using var output = File.Open("C:/stuffs/result.png", FileMode.Create, FileAccess.Write);

var fl = new FrameSizeLimit(42240, 23760, 1004);

var r = await job.Decode(input, false)
    .ResizerCommands("width=250&height=250")
    .EncodeToStream(output, false, new MozJpegEncoder(90, true))
    .Finish()
    .SetSecurityOptions(new SecurityOptions().SetMaxDecodeSize(fl).SetMaxFrameSize(fl).SetMaxEncodeSize(fl))
    .InProcessAsync();

```

**Comment by lilith** [comment]
I would suggest libvips for images that are 2 billion pixels wide.... It
might not compress images as optimally or be as precise, but it handles
huge images well.

**Comment by zlepper** [comment]
I assume by "wide" you are referring to the byte array that backs everything, and not the image width itself, since the image is "only" 50000 something pixels wide? 

We already have a working imagemagick implementation, so no biggie, i was just exploring alternatives, and saw you had a ticket where you wanted feedback, so hoped i could provide some info that could help make the project better :) Either way, have a great day, and stay safe :)

**Comment by lilith** [comment]
Thank you so much! You have a great day too!
