### ISSUE TITLE
Max retires : server denies requests made in rapid succession 

### ISSUE THREAD

**Issue by jramapuram** [imazen/imageflow#207]
Is it possible to prevent ‘imageflow_server’ from denying requests sent in rapid succession?

 I am currently using python ‘requests’ to parallel query crops from the binary version of ‘imageflow_server’ on localhost. My use case is Machine learning where I need ultra fast queries. I seem to run into a max retries error.

Is there some flag or cert strategy that would allow to use this without the following issue?

**Comment by jramapuram** [comment]
The server has no error logs; Here is the python stacktrace:

```bash
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/opt/conda/lib/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/opt/conda/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/conda/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/conda/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/conda/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/opt/conda/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/opt/conda/lib/python3.6/site-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/opt/conda/lib/python3.6/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fc94e973cf8>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/opt/conda/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/opt/conda/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=39876): Max retries exceeded with url: /datasets/cluttered_imagefolder_jpeg_100x100_v3/train_large/2/5898.jpg?crop=33,34,63,63 (Caused by NewConnectionError('<urll
ib3.connection.HTTPConnection object at 0x7fc94e973cf8>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

Note that http://localhost:39876/datasets/cluttered_imagefolder_jpeg_100x100_v3/train_large/2/5898.jpg?crop=33,34,63,63 works **fine** from a browser.

I'm using a simple solution: 

- joblib to spinup 20 threads
- following logic:

```python
        url = "http://localhost:39876{}?crop={},{},{},{}".format(
            self.path,
            top_left[0], top_left[1],
            bottom_right[0], bottom_right[1]
        )
        req = requests.get(url)
        return Image.open(StringIO(req.content))
```
