### ISSUE TITLE
Missing libimageflow.so in docker on windows (.net)

### ISSUE THREAD

**Issue by patsadow2** [imazen/imageflow#212]
Hello,  I've got issue from my dockerfile, please ? :(
```

FROM microsoft/dotnet:2.1-sdk AS build-env
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore

# Copy everything else and build
COPY . ./
RUN dotnet publish -c Release -o out

# Build runtime image
FROM microsoft/dotnet:2.1-aspnetcore-runtime
WORKDIR /app
COPY --from=build-env /app/out .



"System.DllNotFoundException: 'Using "lib[basename].so" Subdir="x64", IsUnix=True, IsDotNetCore=True
Before searching: Unable to load shared library 'imageflow' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libimageflow: cannot open shared object file: No such file or directory
File not found: /app/bin/Debug/netcoreapp2.1/x64/libimageflow.so
File not found: /app/bin/Debug/netcoreapp2.1/libimageflow.so
File not found: /root/.nuget/packages/imageflow.net/0.2.6/lib/netstandard2.0/x64/libimageflow.so
File not found: /root/.nuget/packages/imageflow.net/0.2.6/lib/netstandard2.0/libimageflow.so
   at Imageflow.Bindings.NativeMethods.imageflow_context_create(UInt32 imageflow_abi_ver_major, UInt32 imageflow_abi_ver_minor)
   at Imageflow.Bindings.JobContextHandle.<>c.<.ctor>b__0_0()
   at Imageflow.Bindings.NativeLibraryLoader.FixDllNotFoundException[T](String basename, Func`1 invokingOperation, IEnumerable`1 customSearchDirectories)"

```
![image](https://user-images.githubusercontent.com/19226186/56847168-035a8780-68d8-11e9-9128-f5fbea90de57.png)

Should i somehow adjust it to make it work ?

**Comment by lilith** [comment]
Currently we only support Ubuntu 16 and 18, but you're targeting Debian 9. 

Try `mcr.microsoft.com/dotnet/core/sdk:2.2-bionic` per https://hub.docker.com/_/microsoft-dotnet-core-sdk/
