### ISSUE TITLE
Build failed: thread 'main' panicked at 'include paths from lcms2-sys'

### ISSUE THREAD

**Issue by jl-a** [imazen/imageflow#307]
I get an error when trying to build on Arch based Linux (Manjaro 18.04).

`./build.sh release`

```
...
   Compiling hyper-openssl v0.7.1
   Compiling hyper-native-tls v0.3.0
error: failed to run custom build command for `imageflow_c_components v0.1.0 (/home/jla/Coding/imageflow/c_components)`

Caused by:
  process didn't exit successfully: `/home/jla/Coding/imageflow/target/release/build/imageflow_c_components-ee9b5325e0b73d4e/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'include paths from lcms2-sys', src/libcore/option.rs:1034:5
stack backtrace:
   0:     0x561963fdbd3b - backtrace::backtrace::libunwind::trace::hfe5db90796807973
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1:     0x561963fdbd3b - backtrace::backtrace::trace_unsynchronized::h34b865a835594335
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2:     0x561963fdbd3b - std::sys_common::backtrace::_print::h527254ae44989167
                               at src/libstd/sys_common/backtrace.rs:47
   3:     0x561963fdbd3b - std::sys_common::backtrace::print::he85dd5ddddf46503
                               at src/libstd/sys_common/backtrace.rs:36
   4:     0x561963fdbd3b - std::panicking::default_hook::{{closure}}::h847a2eb38b396f14
                               at src/libstd/panicking.rs:200
   5:     0x561963fdba17 - std::panicking::default_hook::h2ca0f9a30a0e206b
                               at src/libstd/panicking.rs:214
   6:     0x561963fdc4b0 - std::panicking::rust_panic_with_hook::hffcefc09751839d1
                               at src/libstd/panicking.rs:477
   7:     0x561963fdc032 - std::panicking::continue_panic_fmt::hc0f142c930c846fc
                               at src/libstd/panicking.rs:384
   8:     0x561963fdbf16 - rust_begin_unwind
                               at src/libstd/panicking.rs:311
   9:     0x561963ff7afd - core::panicking::panic_fmt::h2daf88b2616ca2b2
                               at src/libcore/panicking.rs:85
  10:     0x561963ff7b67 - core::option::expect_failed::h4b77ebe6e62ec3a1
                               at src/libcore/option.rs:1034
  11:     0x561963f91eda - core::option::Option<T>::expect::h99434f9687c547db
                               at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/option.rs:314
  12:     0x561963f91eda - build_script_build::main::hde61297d850ecb3e
                               at c_components/build.rs:19
  13:     0x561963f926e3 - std::rt::lang_start::{{closure}}::h512e208ed5d7bdb5
                               at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/rt.rs:64
  14:     0x561963fdbeb3 - std::rt::lang_start_internal::{{closure}}::h447d8812e3ee306d
                               at src/libstd/rt.rs:49
  15:     0x561963fdbeb3 - std::panicking::try::do_call::h4a61cb372364c745
                               at src/libstd/panicking.rs:296
  16:     0x561963fe45fa - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:82
  17:     0x561963fdca7d - std::panicking::try::hdf71f938885bca42
                               at src/libstd/panicking.rs:275
  18:     0x561963fdca7d - std::panic::catch_unwind::h7e85dbf162b1611a
                               at src/libstd/panic.rs:394
  19:     0x561963fdca7d - std::rt::lang_start_internal::h1e06cc26b9fc25ea
                               at src/libstd/rt.rs:48
  20:     0x561963f920e8 - main
  21:     0x7f4912c10ee3 - __libc_start_main
  22:     0x561963f9017e - _start
  23:                0x0 - <unknown>

warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `imageflow_c_components v0.1.0 (/home/jla/Coding/imageflow/c_components)`

Caused by:
  process didn't exit successfully: `/home/jla/Coding/imageflow/target/release/build/imageflow_c_components-ee9b5325e0b73d4e/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'include paths from lcms2-sys', src/libcore/option.rs:1034:5
stack backtrace:
   0:     0x55b8fea46d3b - backtrace::backtrace::libunwind::trace::hfe5db90796807973
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1:     0x55b8fea46d3b - backtrace::backtrace::trace_unsynchronized::h34b865a835594335
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2:     0x55b8fea46d3b - std::sys_common::backtrace::_print::h527254ae44989167
                               at src/libstd/sys_common/backtrace.rs:47
   3:     0x55b8fea46d3b - std::sys_common::backtrace::print::he85dd5ddddf46503
                               at src/libstd/sys_common/backtrace.rs:36
   4:     0x55b8fea46d3b - std::panicking::default_hook::{{closure}}::h847a2eb38b396f14
                               at src/libstd/panicking.rs:200
   5:     0x55b8fea46a17 - std::panicking::default_hook::h2ca0f9a30a0e206b
                               at src/libstd/panicking.rs:214
   6:     0x55b8fea474b0 - std::panicking::rust_panic_with_hook::hffcefc09751839d1
                               at src/libstd/panicking.rs:477
   7:     0x55b8fea47032 - std::panicking::continue_panic_fmt::hc0f142c930c846fc
                               at src/libstd/panicking.rs:384
   8:     0x55b8fea46f16 - rust_begin_unwind
                               at src/libstd/panicking.rs:311
   9:     0x55b8fea62afd - core::panicking::panic_fmt::h2daf88b2616ca2b2
                               at src/libcore/panicking.rs:85
  10:     0x55b8fea62b67 - core::option::expect_failed::h4b77ebe6e62ec3a1
                               at src/libcore/option.rs:1034
  11:     0x55b8fe9fceda - core::option::Option<T>::expect::h99434f9687c547db
                               at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/option.rs:314
  12:     0x55b8fe9fceda - build_script_build::main::hde61297d850ecb3e
                               at c_components/build.rs:19
  13:     0x55b8fe9fd6e3 - std::rt::lang_start::{{closure}}::h512e208ed5d7bdb5
                               at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/rt.rs:64
  14:     0x55b8fea46eb3 - std::rt::lang_start_internal::{{closure}}::h447d8812e3ee306d
                               at src/libstd/rt.rs:49
  15:     0x55b8fea46eb3 - std::panicking::try::do_call::h4a61cb372364c745
                               at src/libstd/panicking.rs:296
  16:     0x55b8fea4f5fa - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:82
  17:     0x55b8fea47a7d - std::panicking::try::hdf71f938885bca42
                               at src/libstd/panicking.rs:275
  18:     0x55b8fea47a7d - std::panic::catch_unwind::h7e85dbf162b1611a
                               at src/libstd/panic.rs:394
  19:     0x55b8fea47a7d - std::rt::lang_start_internal::h1e06cc26b9fc25ea
                               at src/libstd/rt.rs:48
  20:     0x55b8fe9fd0e8 - main
  21:     0x7fc90347bee3 - __libc_start_main
  22:     0x55b8fe9fb17e - _start
  23:                0x0 - <unknown>

warning: build failed, waiting for other jobs to finish...
error: build failed
```

I checked for lcms2: `pacman -Qi lcms2`

```
Name            : lcms2
Version         : 2.9-2
...
```

**Comment by kornelski** [comment]
You may need to install lcms2-devel or some other variant of the package that installs C headers in addition to the library binary.

**Comment by jl-a** [comment]
Thanks, yes the pkg-config for lcms2 wasn't correctly set up so couldn't find the headers. Thanks for the help

**Comment by Lythenas** [comment]
@jl-a I'm also on Arch and having the same Problem. How did you fix it?
