### ISSUE TITLE
Azure Web App (Code,Linux,Net7) Error: Looking for "libimageflow.so"

### ISSUE THREAD

**Issue by ollejacobsen** [imazen/imageflow#634]
Hi.

We have setup an Web App on Azure. Using: 
- Publish: Code
- Runtime stack: .NET 7 (STS)
- OS: Linux

After publish and trying to rescale an image we get the Exception:
```
DllNotFoundException: Looking for "libimageflow.so" RID="linux-x64", IsUnix=True, IsDotNetCore=True RelativeSearchPath="" 
Before searching: Unable to load shared library 'imageflow' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable: 
/home/site/wwwroot/imageflow.so: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.9/imageflow.so: cannot open shared object file: No such file or directory
/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/site/wwwroot/libimageflow.so)
/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.9/libimageflow.so: cannot open shared object file: No such file or directory
/home/site/wwwroot/imageflow: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.9/imageflow: cannot open shared object file: No such file or directory
/home/site/wwwroot/libimageflow: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.9/libimageflow: cannot open shared object file: No such file or directory File not found: 
/home/site/wwwroot/x64/libimageflow.so Error "Success" (0) loading imageflow from /home/site/wwwroot/libimageflow.so File not found: 
/home/site/wwwroot/runtimes/linux-x64/native/libimageflow.so at Imageflow.Bindings.NativeMethods.imageflow_context_create(UInt32 imageflowAbiVerMajor, UInt32 imageflowAbiVerMinor) at Imageflow.Bindings.JobContextHandle.<>c.<.ctor>b__0_0() at Imageflow.Bindings.NativeLibraryLoader.FixDllNotFoundException[T](String basename, Func`1 invokingOperation, IEnumerable`1 customSearchDirectories)
```

The Imageflow NuGet packages the project is referencing is:
```
<PackageReference Include="Imageflow.AllPlatforms" Version="0.10.0" />
<PackageReference Include="Imageflow.Server" Version="0.8.1" />
<PackageReference Include="Imageflow.Server.DiskCache" Version="0.8.1" />
```

Should Imageflow be able to run in this simplistic setup?
Locally we are developing on both Windows and OSX without any issues.

Best regads,
Olle

**Comment by lilith** [comment]
Something is going wrong during publish because the transitive depedency
isn't getting copied..

Try adding
https://www.nuget.org/packages/Imageflow.NativeRuntime.ubuntu-x86_64/2.0.0-preview5
directly.

**Comment by ollejacobsen** [comment]
Thanks for the quick reply.

I've tested with the package above with the same result.

If I SSH into the host from the Kudo console and run `cat /etc/os-release`

```
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

Looks that the default container for using an Azure Web App with .NET 7 in Linux is using Debian.

**Comment by lilith** [comment]
It targets RID linux-x64

Even if for some reason your platform didn’t have libc it should still copy
(it is built on Ubuntu 20, but statically links dependencies except for
that one)

Buster is 2019 era, an odd choice, but this is a 64 bit build right?

**Comment by ollejacobsen** [comment]
The build/publish is done in GitHub Actions. And the artifact is copied over to the "Debian" instance.
The job is specifying: `runs-on: ubuntu-latest`
And the publish step is: `dotnet publish {projectname}.csproj -c Release -r linux-x64 --self-contained false` 
I've also tried to omit the -r flag (build for all) and also set --self-contained true. With out any luck.

**Comment by ollejacobsen** [comment]
The `libimageflow.so` file is there and seems to be found (last row).
```
/home/site/wwwroot/runtimes/linux-x64/native/libimageflow.so at Imageflow.Bindings.NativeMethods.imageflow_context_create(UInt32 imageflowAbiVerMajor, UInt32 imageflowAbiVerMinor) at Imageflow.Bindings.JobContextHandle.<>c.<.ctor>b__0_0() at Imageflow.Bindings.NativeLibraryLoader.FixDllNotFoundException[T](String basename, Func`1 invokingOperation, IEnumerable`1 customSearchDirectories)
``` 

Isn't it the depencency `GLIBC_2.29` that's the problem?

**Comment by lilith** [comment]
I don't know from the stacktrace, but have you tried a modern debian?

**Comment by lilith** [comment]
I'm sorry, I just realized the wrapping on my phone occluded the important bit. You are correct, you have a glibc that is too old.  
`/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found`

We build Imageflow on Ubuntu 20.04, the oldest Github Actions offers (and the oldest Ubuntu still patched), which uses `libc 2.31-0ubuntu9.9`

I'd like more info on how Azure put you on such an old platform, Buster EOL was [2022-09-10](https://www.debian.org/News/2022/20220910)

**Comment by ollejacobsen** [comment]
Exactly @lilith it seems a bit weird. I'll try to create a new Web App and check if they have updated the container.
I'll post here again when I have more info.

**Comment by bwaldron-spectrum** [comment]
I confirm the same issue with v0.10 running on a Linux Azure App Service.  App services are all the default Debian, provisioned approximately a year ago, with the same host info as @ollejacobsen.  I suppose workarounds are custom containers, creating fresh, or running apt-get to update glibc, but seems like either may be too much if in a production environment for most.

**Comment by lilith** [comment]
Hmm, that is a challenge. While my own code can switch to linking against
MUSL, it may be tricky for dependencies like mozjpeg/libpng/libwebp. I'll
have to explore options.

No idea why they're deploying an EOL OS.

**Comment by lilith** [comment]
After days of trying to create a musl build, it turns out musl/rust doesn't support making dynamic libraries at all.

Short of using docker images within github actions, it will be hard to reduce the glibc version. I wonder if providing a glibc binary in the nuget package is reasonable?

**Comment by lilith** [comment]
We now parse our produced .so files to verify what glibc they actually depend on, and validate this against a configured 'maximum'. For linux-x64, this is glibc 2.17. 

https://github.com/imazen/imageflow/blob/f1a0e1ad59eaa888f5c1a6ead108df428c8752da/.github/workflows/ci.yml#L47
