### ISSUE TITLE
possible to run in alpine container?

### ISSUE THREAD

**Issue by Wolfmarsh** [imazen/imageflow#644]
Is it possible to run this in an alpine container?

I am trying to do that and running into the exception below.   The same build/deploy works on a chiseled container.  This is potentially due to alpine using musl C, maybe?

Anyone run into this before and have any thoughts?

`Looking for "libimageflow.so" RID="linux-x64", IsUnix=True, IsDotNetCore=True RelativeSearchPath=""
Before searching: Unable to load shared library 'imageflow' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable: 
Error loading shared library /app/runtimes/linux-x64/native/imageflow.so: No such file or directory
Error loading shared library /usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.2/imageflow.so: No such file or directory
Error loading shared library /app/imageflow.so: No such file or directory
Error loading shared library imageflow.so: No such file or directory
Error loading shared library libmvec.so.1: No such file or directory (needed by /app/runtimes/linux-x64/native/libimageflow.so)
Error loading shared library /usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.2/libimageflow.so: No such file or directory
Error loading shared library /app/libimageflow.so: No such file or directory
Error loading shared library libimageflow.so: No such file or directory
Error loading shared library /app/runtimes/linux-x64/native/imageflow: No such file or directory
Error loading shared library /usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.2/imageflow: No such file or directory
Error loading shared library /app/imageflow: No such file or directory
Error loading shared library imageflow: No such file or directory
Error loading shared library /app/runtimes/linux-x64/native/libimageflow: No such file or directory
Error loading shared library /usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.2/libimageflow: No such file or directory
Error loading shared library /app/libimageflow: No such file or directory
Error loading shared library libimageflow: No such file or directory

File not found: /app/x64/libimageflow.so
File not found: /app/libimageflow.so
Error "No such file or directory" (2) loading imageflow from /app/runtimes/linux-x64/native/libimageflow.so
   at Imageflow.Bindings.NativeMethods.imageflow_context_create(UInt32 imageflowAbiVerMajor, UInt32 imageflowAbiVerMinor)
   at Imageflow.Bindings.JobContextHandle.<>c.<.ctor>b__0_0()
   at Imageflow.Bindings.NativeLibraryLoader.FixDllNotFoundException[T](String basename, Func`1 invokingOperation, IEnumerable`1 customSearchDirectories)`

**Comment by lilith** [comment]
Right now we don't have a musl build, so a newish libc is required - which
excludes Alpine. I would love a PR for a linux musl build, though!

**Comment by acj** [comment]
If it helps anyone, there's an [imageflow package](https://pkgs.alpinelinux.org/package/edge/community/x86_64/imageflow) for Alpine that can be installed with `apk add imageflow`. (I'm the package maintainer.) I'm a fan of this project but not currently an active user, so it's possible that the package is missing some tools or features. If you run into any issues, let me know.

> I would love a PR for a linux musl build, though!

The [APKBUILD file](https://gitlab.alpinelinux.org/alpine/aports/-/blob/master/community/imageflow/APKBUILD) shows the set of packages that need to be installed in a Docker environment. It should be straightforward to produce a musl-based binary.

@lilith While we're here - it would be great to have a more recent git tag/release for packaging purposes. 2.0.0-preview8 fails to build for me, but the tip of main is healthy. Thanks for all your work on these tools!
